; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -mtriple=spirv64-unknown-unknown -passes=sroa -S | FileCheck %s --check-prefix=SPIRV
; RUN: opt < %s -mtriple=x86_64-unknown-linux-gnu -passes=sroa -S | FileCheck %s --check-prefix=X86

target datalayout = "e-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-n8:16:32:64"

%MixedNode = type { [6 x float], i16, i8, [5 x i8] }
%AllWordNode = type { [6 x float], i32, i32 }

; When a 32-byte struct has 1-byte/2-byte stores alongside a <8 x i32> load,
; SROA must not promote the alloca to <32 x i8> on SPIR-V targets (since SPIR-V
; only supports 2, 3, 4, 8, and 16 component vectors).
define <8 x i32> @mixed_granularity_32byte_no_v32i8(float %f0, i16 %mask, i8 %flags) {
; SPIRV-LABEL: define <8 x i32> @mixed_granularity_32byte_no_v32i8(
; SPIRV-SAME: float [[F0:%.*]], i16 [[MASK:%.*]], i8 [[FLAGS:%.*]]) {
; SPIRV-NEXT:  [[ENTRY:.*:]]
; SPIRV-NEXT:    [[NODE_SROA_0:%.*]] = alloca <8 x i32>, align 32
; SPIRV-NEXT:    store float [[F0]], ptr [[NODE_SROA_0]], align 32
; SPIRV-NEXT:    [[NODE_SROA_0_24_MASK_PTR_SROA_IDX1:%.*]] = getelementptr inbounds i8, ptr [[NODE_SROA_0]], i64 24
; SPIRV-NEXT:    store i16 [[MASK]], ptr [[NODE_SROA_0_24_MASK_PTR_SROA_IDX1]], align 8
; SPIRV-NEXT:    [[NODE_SROA_0_26_FLAGS_PTR_SROA_IDX2:%.*]] = getelementptr inbounds i8, ptr [[NODE_SROA_0]], i64 26
; SPIRV-NEXT:    store i8 [[FLAGS]], ptr [[NODE_SROA_0_26_FLAGS_PTR_SROA_IDX2]], align 2
; SPIRV-NEXT:    [[NODE_SROA_0_0_NODE_SROA_0_0_VEC:%.*]] = load <8 x i32>, ptr [[NODE_SROA_0]], align 32
; SPIRV-NEXT:    ret <8 x i32> [[NODE_SROA_0_0_NODE_SROA_0_0_VEC]]
;
; X86-LABEL: define <8 x i32> @mixed_granularity_32byte_no_v32i8(
; X86-SAME: float [[F0:%.*]], i16 [[MASK:%.*]], i8 [[FLAGS:%.*]]) {
; X86-NEXT:  [[ENTRY:.*:]]
; X86-NEXT:    [[TMP0:%.*]] = bitcast float [[F0]] to <4 x i8>
; X86-NEXT:    [[NODE_SROA_0_0_VEC_EXPAND:%.*]] = shufflevector <4 x i8> [[TMP0]], <4 x i8> poison, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; X86-NEXT:    [[NODE_SROA_0_0_VECBLEND:%.*]] = shufflevector <32 x i8> [[NODE_SROA_0_0_VEC_EXPAND]], <32 x i8> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; X86-NEXT:    [[TMP1:%.*]] = bitcast i16 [[MASK]] to <2 x i8>
; X86-NEXT:    [[NODE_SROA_0_24_VEC_EXPAND:%.*]] = shufflevector <2 x i8> [[TMP1]], <2 x i8> poison, <32 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; X86-NEXT:    [[NODE_SROA_0_24_VECBLEND:%.*]] = shufflevector <32 x i8> [[NODE_SROA_0_24_VEC_EXPAND]], <32 x i8> [[NODE_SROA_0_0_VECBLEND]], <32 x i32> <i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 24, i32 25, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; X86-NEXT:    [[NODE_SROA_0_26_VEC_INSERT:%.*]] = insertelement <32 x i8> [[NODE_SROA_0_24_VECBLEND]], i8 [[FLAGS]], i64 26
; X86-NEXT:    [[TMP2:%.*]] = bitcast <32 x i8> [[NODE_SROA_0_26_VEC_INSERT]] to <8 x i32>
; X86-NEXT:    ret <8 x i32> [[TMP2]]
;
entry:
  %node = alloca %MixedNode, align 32
  store float %f0, ptr %node, align 32
  %mask.ptr = getelementptr inbounds i8, ptr %node, i64 24
  store i16 %mask, ptr %mask.ptr, align 8
  %flags.ptr = getelementptr inbounds i8, ptr %node, i64 26
  store i8 %flags, ptr %flags.ptr, align 2
  %vec = load <8 x i32>, ptr %node, align 32
  ret <8 x i32> %vec
}

; When all scalar accesses are 4-byte words matching the <8 x i32> element size,
; SROA should still promote the alloca to <8 x i32> on SPIR-V (8 is a valid
; SPIR-V vector size).
define <8 x i32> @all_word_32byte_promotes_to_v8i32(float %f0, i32 %mask, i32 %pad) {
; SPIRV-LABEL: define <8 x i32> @all_word_32byte_promotes_to_v8i32(
; SPIRV-SAME: float [[F0:%.*]], i32 [[MASK:%.*]], i32 [[PAD:%.*]]) {
; SPIRV-NEXT:  [[ENTRY:.*:]]
; SPIRV-NEXT:    [[TMP0:%.*]] = bitcast float [[F0]] to i32
; SPIRV-NEXT:    [[NODE_SROA_0_0_VEC_INSERT:%.*]] = insertelement <8 x i32> undef, i32 [[TMP0]], i64 0
; SPIRV-NEXT:    [[NODE_SROA_0_24_VEC_INSERT:%.*]] = insertelement <8 x i32> [[NODE_SROA_0_0_VEC_INSERT]], i32 [[MASK]], i64 6
; SPIRV-NEXT:    [[NODE_SROA_0_28_VEC_INSERT:%.*]] = insertelement <8 x i32> [[NODE_SROA_0_24_VEC_INSERT]], i32 [[PAD]], i64 7
; SPIRV-NEXT:    ret <8 x i32> [[NODE_SROA_0_28_VEC_INSERT]]
;
; X86-LABEL: define <8 x i32> @all_word_32byte_promotes_to_v8i32(
; X86-SAME: float [[F0:%.*]], i32 [[MASK:%.*]], i32 [[PAD:%.*]]) {
; X86-NEXT:  [[ENTRY:.*:]]
; X86-NEXT:    [[TMP0:%.*]] = bitcast float [[F0]] to i32
; X86-NEXT:    [[NODE_SROA_0_0_VEC_INSERT:%.*]] = insertelement <8 x i32> undef, i32 [[TMP0]], i64 0
; X86-NEXT:    [[NODE_SROA_0_24_VEC_INSERT:%.*]] = insertelement <8 x i32> [[NODE_SROA_0_0_VEC_INSERT]], i32 [[MASK]], i64 6
; X86-NEXT:    [[NODE_SROA_0_28_VEC_INSERT:%.*]] = insertelement <8 x i32> [[NODE_SROA_0_24_VEC_INSERT]], i32 [[PAD]], i64 7
; X86-NEXT:    ret <8 x i32> [[NODE_SROA_0_28_VEC_INSERT]]
;
entry:
  %node = alloca %AllWordNode, align 32
  store float %f0, ptr %node, align 32
  %mask.ptr = getelementptr inbounds i8, ptr %node, i64 24
  store i32 %mask, ptr %mask.ptr, align 8
  %pad.ptr = getelementptr inbounds i8, ptr %node, i64 28
  store i32 %pad, ptr %pad.ptr, align 4
  %vec = load <8 x i32>, ptr %node, align 32
  ret <8 x i32> %vec
}

; When a 32-byte alloca has a 24-byte (6 x i32) partial memcpy alongside a
; <8 x i32> load, SROA must not synthesize a 6-element <6 x i32> slice vector
; on SPIR-V.
define <8 x i32> @partial_memcpy_24byte_no_v6i32(ptr %src, i32 %mask, i32 %pad) {
; SPIRV-LABEL: define <8 x i32> @partial_memcpy_24byte_no_v6i32(
; SPIRV-SAME: ptr [[SRC:%.*]], i32 [[MASK:%.*]], i32 [[PAD:%.*]]) {
; SPIRV-NEXT:  [[ENTRY:.*:]]
; SPIRV-NEXT:    [[NODE_SROA_0:%.*]] = alloca <8 x i32>, align 32
; SPIRV-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 32 [[NODE_SROA_0]], ptr align 4 [[SRC]], i64 24, i1 false)
; SPIRV-NEXT:    [[NODE_SROA_0_24_MASK_PTR_SROA_IDX1:%.*]] = getelementptr inbounds i8, ptr [[NODE_SROA_0]], i64 24
; SPIRV-NEXT:    store i32 [[MASK]], ptr [[NODE_SROA_0_24_MASK_PTR_SROA_IDX1]], align 8
; SPIRV-NEXT:    [[NODE_SROA_0_28_PAD_PTR_SROA_IDX2:%.*]] = getelementptr inbounds i8, ptr [[NODE_SROA_0]], i64 28
; SPIRV-NEXT:    store i32 [[PAD]], ptr [[NODE_SROA_0_28_PAD_PTR_SROA_IDX2]], align 4
; SPIRV-NEXT:    [[NODE_SROA_0_0_NODE_SROA_0_0_VEC:%.*]] = load <8 x i32>, ptr [[NODE_SROA_0]], align 32
; SPIRV-NEXT:    ret <8 x i32> [[NODE_SROA_0_0_NODE_SROA_0_0_VEC]]
;
; X86-LABEL: define <8 x i32> @partial_memcpy_24byte_no_v6i32(
; X86-SAME: ptr [[SRC:%.*]], i32 [[MASK:%.*]], i32 [[PAD:%.*]]) {
; X86-NEXT:  [[ENTRY:.*:]]
; X86-NEXT:    [[NODE_SROA_0_0_COPYLOAD:%.*]] = load <6 x i32>, ptr [[SRC]], align 4
; X86-NEXT:    [[NODE_SROA_0_0_VEC_EXPAND:%.*]] = shufflevector <6 x i32> [[NODE_SROA_0_0_COPYLOAD]], <6 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 poison, i32 poison>
; X86-NEXT:    [[NODE_SROA_0_0_VECBLEND:%.*]] = shufflevector <8 x i32> [[NODE_SROA_0_0_VEC_EXPAND]], <8 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 14, i32 15>
; X86-NEXT:    [[NODE_SROA_0_24_VEC_INSERT:%.*]] = insertelement <8 x i32> [[NODE_SROA_0_0_VECBLEND]], i32 [[MASK]], i64 6
; X86-NEXT:    [[NODE_SROA_0_28_VEC_INSERT:%.*]] = insertelement <8 x i32> [[NODE_SROA_0_24_VEC_INSERT]], i32 [[PAD]], i64 7
; X86-NEXT:    ret <8 x i32> [[NODE_SROA_0_28_VEC_INSERT]]
;
entry:
  %node = alloca %AllWordNode, align 32
  call void @llvm.memcpy.p0.p0.i64(ptr align 32 %node, ptr align 4 %src, i64 24, i1 false)
  %mask.ptr = getelementptr inbounds i8, ptr %node, i64 24
  store i32 %mask, ptr %mask.ptr, align 8
  %pad.ptr = getelementptr inbounds i8, ptr %node, i64 28
  store i32 %pad, ptr %pad.ptr, align 4
  %vec = load <8 x i32>, ptr %node, align 32
  ret <8 x i32> %vec
}

declare void @llvm.memcpy.p0.p0.i64(ptr noalias nocapture writeonly, ptr noalias nocapture readonly, i64, i1 immarg)
